LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Manager.csv' INTO TABLE MANAGER FIELDS TERMINATED BY ',';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Team.csv' INTO TABLE TEAM FIELDS TERMINATED BY ',';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Player.csv' INTO TABLE PLAYER FIELDS TERMINATED BY ',';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Injury.csv' INTO TABLE INJURY FIELDS TERMINATED BY ',';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Game.csv' INTO TABLE GAME FIELDS TERMINATED BY ',';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Manager_On_Game.csv' INTO TABLE MANAGER_ON_GAME FIELDS TERMINATED BY ',';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/TeamSquad.csv' INTO TABLE TEAM_SQUAD FIELDS TERMINATED BY ',';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Goal.csv' INTO TABLE GOAL FIELDS TERMINATED BY ',';